---
- hosts: HOST
  vars:
    grafana_version: 2.5.0
    arch: amd64
    grafana_filename: grafana_{{ grafana_version }}_{{ arch }}.deb

  tasks:
  - name: Verify version
    command: dpkg-query -W --showformat='${version}' grafana
    register: grafana_check_version
    failed_when: grafana_check_version.rc > 1
    changed_when: (grafana_check_version.rc == 1) or
                  (grafana_check_version | version_compare("{{ grafana_version }}", "<"))

  - name: Download grafana deb file
    get_url:
      url="https://grafanarel.s3.amazonaws.com/builds/{{ grafana_filename }}"
      dest="/tmp/{{ grafana_filename }}"
    when: grafana_check_version.changed

  - name: Verify grafana deb file
    command: dpkg-deb -W --showformat='${version}' /tmp/{{ grafana_filename }}
    register: grafana_deb_check_version
    failed_when: grafana_deb_check_version.stdout != "{{ grafana_version }}"
    when: grafana_check_version.changed

  - name: Install grafana
    apt: deb="/tmp/{{ grafana_filename }}" state=present
    when: grafana_check_version.changed